### ISSUE TITLE
no method named `fetch_credentials_same_origin` found for struct `RequestBuilder` in the current scope

### ISSUE THREAD

**Issue by andoriyu** [devashishdxt/tonic-web-wasm-client#1]
In `0.1.1`:

```
error[E0599]: no method named `fetch_credentials_same_origin` found for struct `RequestBuilder` in the current scope
  --> /home/andoriyu/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-web-wasm-client-0.1.1/src/client.rs:60:10
   |
60 |         .fetch_credentials_same_origin();
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `RequestBuilder`
```

**Comment by devashishdxt** [comment]
Try building it with `--target wasm32-unknown-unknown`

**Comment by andoriyu** [comment]
> Try building it with `--target wasm32-unknown-unknown`. This crate is only for use in browsers using wasm.

@devashishdxt  oh weird. My wasm crate is just in workspace with other crates and `cargo check` generally just worked fine. Anyways, setting target fixed it.

Any reason you've switched from web-sys's fetch api to `reqwest` in this fork?

**Comment by devashishdxt** [comment]
> Any reason you've switched from web-sys's fetch api to `reqwest` in this fork?

Request internally uses `fetch` API. I preferred it because it has a clean and easy to use API.

**Comment by devashishdxt** [comment]
In addition to that, it'll be easy to extend this crate in future for use outside of browsers to connect to `grpc-web` servers.

**Comment by andoriyu** [comment]
@devashishdxt would you mind if I mark `wasm-only` stuff to be compiled only on `wasm32-unknown-unknown` target? I have a workspace that has wasm and not wasm crates, right now, it can't be built.

[per-pacakge-target](https://doc.rust-lang.org/cargo/reference/unstable.html#per-package-target) is still an unstable feature.

**Comment by devashishdxt** [comment]
I'm not sure what you mean by "mark `wasm-only` stuff to compile". Can you create a PR? So that I can review?
