### ISSUE TITLE
unable to depend on this package under wasm32

### ISSUE THREAD

**Issue by clsx524** [devashishdxt/tonic-web-wasm-client#18]
Hi, I have a project integrated with this repo however when i ran `cargo build --target wasm32-unknown-unknown` it would fail with errors.
```
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /home/clsx524/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/clsx524/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/net/tcp/listener.rs:15:17
   |
15 | use crate::sys::tcp::{bind, listen, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/clsx524/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/net/tcp/stream.rs:13:17
   |
13 | use crate::sys::tcp::{connect, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0433]: failed to resolve: could not find `Selector` in `sys`
   --> /home/clsx524/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/poll.rs:301:18
    |
301 |             sys::Selector::new().map(|selector| Poll {
    |                  ^^^^^^^^ could not find `Selector` in `sys`

.......
```

It was trying to compile with mio and it would definitely fail. I can verify tonic-web-wasm-client is the only package requesting it because after I removed it from Cargo.toml, it won't complain this error any more.

This is my setup in Cargo.toml
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic-web-wasm-client = "0.2.2"
```
How should I correctly depend on this package?

**Comment by devashishdxt** [comment]
I faced the same issue and it seems that the problem is with cargo dependency resolver. As a workaround, you can try using a feature instead of `[target.'cfg(target_arch = "wasm32")'.dependencies]`. Here is an example: https://github.com/devashishdxt/stag/blob/f0143fe8d58e91a7e91066a2e77b73361d043eac/stag-api/Cargo.toml#L62

**Comment by clsx524** [comment]
Unfortunately this approach doesn't work for me but I have found a workaround. However, I think `tokio::runtime::Runtime` is not available on wasm so I don't know how to handle async functions under the current scope. what runtime do you use with this package?

**Comment by devashishdxt** [comment]
> what runtime do you use with this package?

Browser's runtime.

**Comment by clsx524** [comment]
Thanks.

**Comment by bishoyroufael** [comment]
I am facing this issue. What's the current solution for it?

**Comment by devashishdxt** [comment]
> I am facing this issue. What's the current solution for it?

Can you share your `Cargo.toml`?
