### ISSUE TITLE
Combined content-type not recognized by tonic

### ISSUE THREAD

**Issue by bit-void** [devashishdxt/tonic-web-wasm-client#3]
I'm using tonic on the backend. The created client mergers the content-type together creating a header that tonic-web does not expect.

For example, tonic-web expects one of these 4 content-types:

https://github.com/hyperium/tonic/blob/8084f4ea26cccf9bd2d96d2a81eaea490aaf603b/tonic-web/src/service.rs#L29-L32
```
    //  - "application/grpc-web"
    //  - "application/grpc-web+proto"
    //  - "application/grpc-web-text"
    //  - "application/grpc-web-text+proto"
```

However, the header `application/grpc` gets combined with the headers added by this client `application/grpc-web+proto". This results in a 400:

```
400 Bad Request
panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Unknown, message: "missing content-type header in grpc response", source: Some(MissingContentTypeHeader) }'
```

The header that is generated by this client looks like this:
```
content-type: application/grpc-web+proto, application/grpc
```

If I modify these lines: https://github.com/devashishdxt/tonic-web-wasm-client/blob/main/src/client.rs#L62-L64 to be this:

```rust
    for (header_name, header_value) in req.headers().iter() {
        if header_name.as_str() != "content-type" {
            builder = builder.header(header_name.as_str(), header_value.to_str()?);
        }
    }
```

it all works. I'm not sure where the `application/grpc` is getting attached, I think it's on the tonic side. Not sure exactly what the resolution here is either.

**Comment by devashishdxt** [comment]
`tonic-web` response should contain `content-type` header. https://github.com/devashishdxt/tonic-web-wasm-client/blob/6b96030a0ad749716bcf8fdd0e0faaf505864b86/src/client.rs#L80

**Comment by bit-void** [comment]
Although I don't think this client should ultimately emit `application/grpc` content-type header at all, since that's wrong.

**Comment by devashishdxt** [comment]
Thanks for opening this issue. I'll check this over the weekend when I get some time.

**Comment by devashishdxt** [comment]
Created a new version on crates.io with a fix: https://crates.io/crates/tonic-web-wasm-client

**Comment by bit-void** [comment]
Thank you! ❤️

**Comment by bit-void** [comment]
@devashishdxt might be worth setting the correct content type in tower per https://github.com/hyperium/tonic/issues/1041#issuecomment-1199578481
