### ISSUE TITLE
tonic::Status `.code()` "Unknown", `message()` "malformed response" for grpc-status: 16 or 5

### ISSUE THREAD

**Issue by isosphere** [devashishdxt/tonic-web-wasm-client#31]
# Version Housekeeping 
`rustc` 1.67.1
`tonic-web-wasm-client` ca7f5c9d1152000d862810accb2df9c60ba2d963

Backend:
`tonic` 0.8
`tonic-web` 0.5

# Report
I think that there might be an issue with error response handling.

I'm implementing an authentication system. If the user inputs a user that doesn't exist, my backend responds with a tonic::Status of Unauthenticated. This has a grpc-status code of 16. 

In testing the client-side portion of this, I'm doing the following:

```rust
use tonic_web_wasm_client::Client;
use gloo_console::error;

let mut query_client: AuthenticationServiceClient<Client> = AuthenticationServiceClient::new(Client::new(BASE_URL.to_owned()));

let response = match query_client.get_authentication_token(request).await {
    Ok(response) => {
            ... login stuff ...
    },
    Err(e) => {
        error!(format!("Error: {:?}, {:?}", e.code(), e.message()));
        error!(format!("Error: {:?}", e));
    }
}
```

If I enter valid credentials authentication proceeds within the `Ok(...)` block as expected.

If I enter invalid credentials, my code does not have appropriate information to provide a good error message to the user. The error `e` always has the following debug print value:

```
Status { code: Unknown, message: "malformed response", metadata: MetadataMap { headers: {"content-length": "0", "content-type": "application/grpc-web+proto"} }, source: Some(MalformedResponse) }
```

However if I inspect the response in the Firefox development console, I see an appropriate grpc-status header code of 16 with an appropriately matching grpc-message header. 

I have also tried responding with `NotFound` which is code 5, but that doesn't change what is exposed as `e`.

**Comment by devashishdxt** [comment]
Hi. Thanks for creating this issue.

I've created a PR to test error responses from server and the test seems to pass: #32.

Can you share your server code so that I have more context on what you're trying to do?

**Comment by isosphere** [comment]
Here's a very abbreviated pseudo-code snippet. This is using Tonic with tonic_web::GrpcWebLayer:
# Main
```rust
async fn main() -> Result<...> {
    let authentication_service_state = MyAuthTokenServer{some_parameter = true};
    let cors = CorsLayer::new()
        .allow_methods([Method::GET, Method::POST, Method::OPTIONS])
        .allow_headers(Any)
        .allow_origin(format!("http://{}:8080", matches.grpc_address).parse::<HeaderValue>().unwrap());

    Server::builder()
        .accept_http1(true) // required for tonic-web; as of this writing it presents as HTTP/1.1
        .layer(cors)
        .layer(CookieManagerLayer::new())
        .layer(GrpcWebLayer::new())
        .add_service(AuthenticationServiceServer::new(authentication_service_state))
        .serve(addr)
        .await?;
    Ok(())
}
```

# Service Implementation
```rust
stuct MyAuthTokenServer{some_parameter: type}

#[tonic::async_trait]
impl AuthenticationService for MyAuthTokenServer {
    async fn get_authentication_token(&self, request: Request<AuthTokenRequest>) -> Result<Response<AuthTokenReponse>, Status> {
        let user_instance = match get_customer_by_email(&mut connection, &request_packet.username) {
            Ok(u) => u,
            Err(e) => {
                warn!("Failed to find user with email {:?}: {:?}", &request_packet.username, e);
                return Err(Status::not_found("Not found"));
            }
        };
    }
}

**Comment by devashishdxt** [comment]
This PR: #32 has almost the same test case which passes. I'm not sure if anything can be done on this crate to fix your issue.

**Comment by devashishdxt** [comment]
Maybe you can review your `cors` configuration. Here's a sample: https://github.com/devashishdxt/tonic-web-wasm-client/blob/ca7f5c9d1152000d862810accb2df9c60ba2d963/test-suite/simple/server/src/main.rs#L116.

**Comment by devashishdxt** [comment]
Closing this issue for now. If you still see the error, please create PR with a test case that fails and feel free to reopen.

**Comment by isosphere** [comment]
I copied and pasted your `CorsLayer` invocation and it resolved the issue, good call.
