### ISSUE TITLE
Request: Support `fetch` Options

### ISSUE THREAD

**Issue by isosphere** [devashishdxt/tonic-web-wasm-client#33]
It doesn't appear that we can specify any options for fetch requests. These can be required for some applications, such as specifying `credentials=include` when cookies are required. 

https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

Other options of note are (based on my own opinion):
- headers
- integrity (checksum validating request payload)
- signal (allow aborting long requests)
- priority

All of these options are supported within the `web_sys::Request` struct that `crate::fetch` takes as an argument; but I don't see how we can manipulate these options in this crate.

It appears that the`credentials` option, for example, is hardcoded: 

https://github.com/devashishdxt/tonic-web-wasm-client/blob/2197c6240b5b262972d28b8610534e16b18a9b91/src/call.rs#L74

I manually set this to `RequestCredentials::Include` locally because I am setting cookies over GRPC and it worked - without this change cookies are not saved.

**Comment by isosphere** [comment]
I started to dig into the code a bit to think about how this could be done. 

I think we'd implement a `FetchOptions` struct to contain whatever options we want to support, probably defined in `call.rs`.  `call` would accept an `Option<FetchOptions>`, limiting the distress this breaking change would cause and allowing users to specify `None` to get the old default behaviour. This would be passed off to `prepare_request` which would either use the given `FetchOptions` or defaults if `None`. 

We could avoid breaking the API by having the default `Client` always specify `None` for these options, and provide a new `ClientWithOptions` for users that want to change the default behaviour.

**Comment by devashishdxt** [comment]
Hi @isosphere. Thanks for creating this issue.

It seems like a good idea to add `FetchOptions`. Will make changes by the end of next week or maybe sooner if it isn't that difficult.

**Comment by devashishdxt** [comment]
Released new version (0.4.0) with support for `FetchOptions`.
