### ISSUE TITLE
Project examples using tonic-web-wasm-client

### ISSUE THREAD

**Issue by NathanielPrescott** [devashishdxt/tonic-web-wasm-client#47]
Hello, 

I was just wondering if there were any examples using this crate.  I am having trouble understanding the crate setup to get this working.  Currently getting 'socket2' could not compile error when building.

Thanks,
Nathan

**Comment by devashishdxt** [comment]
For an example, you can see [test-suite](https://github.com/devashishdxt/tonic-web-wasm-client/tree/main/test-suite/simple). Generally, you get compilation error when you don't compile the project for wasm. As mentioned in the README, try using `cargo build --target wasm32-unknown-unknown`.

**Comment by devashishdxt** [comment]
For a bigger and more complex example, take a look at [stag](https://github.com/devashishdxt/stag/).

**Comment by devashishdxt** [comment]
For a bigger and more complex example, take a look at [stag](https://github.com/devashishdxt/stag/).

**Comment by NathanielPrescott** [comment]
I've followed the 'test-suite' examples and it looks like its building the proto rust file correctly except for the following errors.  I did find that I was building with the same `cargo build --target wasm32-unknown-unknown` on jetbrains ide and it was throwing different errors than in the terminal which was weird.  The below errors are from the terminal.

```
cargo build --target wasm32-unknown-unknown                                                                        101 ✘ 
   Compiling service v0.1.2 (/home/nprescott/Documents/Projects/Performance/gRPCvREST/client/service)
error[E0433]: failed to resolve: could not find `transport` in `tonic`
  --> /home/nprescott/Documents/Projects/Performance/gRPCvREST/client/service/target/wasm32-unknown-unknown/debug/build/service-e5340caf0c74f563/out/imagestorage.rs:34:36
   |
34 |     impl ImageStorageClient<tonic::transport::Channel> {
   |                                    ^^^^^^^^^ could not find `transport` in `tonic`

error[E0433]: failed to resolve: could not find `transport` in `tonic`
  --> /home/nprescott/Documents/Projects/Performance/gRPCvREST/client/service/target/wasm32-unknown-unknown/debug/build/service-e5340caf0c74f563/out/imagestorage.rs:38:31
   |
38 |             D: TryInto<tonic::transport::Endpoint>,
   |                               ^^^^^^^^^ could not find `transport` in `tonic`

error[E0433]: failed to resolve: could not find `transport` in `tonic`
  --> /home/nprescott/Documents/Projects/Performance/gRPCvREST/client/service/target/wasm32-unknown-unknown/debug/build/service-e5340caf0c74f563/out/imagestorage.rs:36:64
   |
36 |         pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
   |                                                                ^^^^^^^^^ could not find `transport` in `tonic`

error[E0433]: failed to resolve: could not find `transport` in `tonic`
  --> /home/nprescott/Documents/Projects/Performance/gRPCvREST/client/service/target/wasm32-unknown-unknown/debug/build/service-e5340caf0c74f563/out/imagestorage.rs:41:31
   |
41 |             let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
   |                               ^^^^^^^^^ could not find `transport` in `tonic`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `service` (lib) due to 4 previous errors
```

Here is what my cargo.toml looks like for my wasm-grpc service:

```
[package]
name = "service"
version = "0.1.2"
edition = "2021"

[dependencies]
prost = "0.12.1"
tonic = { version = "0.10.2", default-features = false, features = [
    "prost",
    "codegen",
] }

[build-dependencies]
tonic-build = "0.10.2"

[dev-dependencies]
tonic-web-wasm-client = "0.5.0"
```

**Comment by NathanielPrescott** [comment]
Oh I did not think the tonic-build needed the default features to also be off with the prost enabled.  Think that fixed my errors.

**Comment by NathanielPrescott** [comment]
I'll close this issue, I currently got it building and working but now just think I have a CORS issue or something similar when interacting between my frontend and backend.  Thank you for the help!
