### ISSUE TITLE
gRPC web coverage 

### ISSUE THREAD

**Issue by huntc** [devashishdxt/tonic-web-wasm-client#50]
Thanks for providing this library!

Are there parts of gRPC-web that remain to be supported?

**Comment by devashishdxt** [comment]
@huntc As fas as I'm aware (my understanding of `grpc-web` protocol may be limited), I haven't tried adding support for any encoding except for protobuf. `grpc-web` also supports `json`, `thrift` or text encodings.

**Comment by huntc** [comment]
Thanks, that provides me with the perspective that this looks like a pretty comprehensive implementation.
