### ISSUE TITLE
error.code() and error handling

### ISSUE THREAD

**Issue by npcnuno** [devashishdxt/tonic-web-wasm-client#57]
I can't get the error code from the backend, making error handling difficult on the client

I always get code = "Unknow error" when I try to get the error code from the backend

#[wasm_bindgen]
pub async fn refresh_token(refresh: String) -> Result<JsValue, JsValue> {
    let mut client = AuthenticationClient::new(build_client());
    let result = client
        .refresh_token_admin(RefreshRequest {
            refresh_token: refresh,
        })
        .await;

    match result {
        Ok(response) => {
            let res = response.into_inner();
            Ok(JsValue::from_str(
                &serde_json::json!({
                "code" : "0",
                "description": res.auth_token.to_string()})
                .to_string(),
            ))
        }
        Err(error) => Err(JsValue::from_str(
            &serde_json::json!({
                "code": error.code().to_string(),
                "description": error.details(),
            })
            .to_string(),
        )),
    }
}

**Comment by devashishdxt** [comment]
Hi. The error code depends on the code that is returned by the server. Can you share some of your server code here?

**Comment by npcnuno** [comment]
Sorry to take so long here is the code:

    async fn refresh_token_admin(
        &self,
        request: Request<RefreshRequest>,
    ) -> Result<Response<RefreshResponse>, Status> {
        let refresh = request.into_inner().refresh_token;
        if !validate_refresh_admin(&refresh) {
            return Err(Status::permission_denied(""));
        }
        let (head, decoded) = decode_refresh(&refresh).unwrap();
        let str: Option<String> = dbconn::redis_get(&decoded.rid).await.unwrap();
        if str.is_none() {
            return Err(Status::internal("couldn't create auth from refresh"));
        }
        let admin = DB
            .query(format!("select * from admin:{}", decoded.uid))
            .await;
        if admin.is_err() {
            return Err(Status::internal("couldn't query db"));
        }
        let admin: Option<Admin> = match admin.unwrap().take(0) {
            Ok(a) => a,
            Err(_) => return Err(Status::internal("couldn't query db")),
        };
        if admin.is_none() {
            return Err(Status::internal("couldn't query db"));
        }
        let admin = admin.unwrap();
        match create_jwt_auth(
            &decoded.uid,
            &admin.institution.id.to_string(),
            Previlege::from_str(&head.typ.unwrap()).unwrap(),
        ) {
            Ok(a) => Ok(Response::new(RefreshResponse { auth_token: a })),
            Err(_) => Err(Status::internal("couldn't create auth from refresh")),
        }
    }

**Comment by npcnuno** [comment]
let admin: Option<Admin> = match admin.unwrap().take(0) {
        Ok(a) => a,
        Err(_) => return Err(Status::internal("couldn't query db")),
    };
    if admin.is_none() {
        return Err(Status::internal("couldn't query db"));
    }
    let admin = admin.unwrap();
    match create_jwt_auth(
        &decoded.uid,
        &admin.institution.id.to_string(),
        Previlege::from_str(&head.typ.unwrap()).unwrap(),
    ) {
        Ok(a) => Ok(Response::new(RefreshResponse { auth_token: a })),
        Err(_) => Err(Status::internal("couldn't create auth from refresh")),
    }
}

**Comment by cyanic-selkie** [comment]
Hi, I'm having the same issue. However, I only started getting the issue once I switched the traefik reverse proxy that handled grpc-web translation with the `tonic_web` crate.

I'm guessing this is an issue with `tonic_web` then. @npcnuno, is your server using that crate as well?

**Comment by npcnuno** [comment]
Yes @cyanic-selkie

**Comment by cyanic-selkie** [comment]
I opened an [issue](https://github.com/hyperium/tonic/issues/1666#issue-2209256609) on the `tonic` repository.

**Comment by devashishdxt** [comment]
Closing this issue

**Comment by imotai** [comment]
> Hi, I'm having the same issue. However, I only started encountering the issue once I swapped the traefik reverse proxy that handled grpc-web translation with the `tonic_web` crate.
> 
> I'm guessing this is an issue with `tonic_web` then. @npcnuno, is your server using that crate as well?

I have the same issue when I use tonic gprc server behind the nginx proxy

**Comment by flisky** [comment]
It's a CORS-related problem, see https://github.com/hyperium/tonic/issues/1666#issuecomment-4088165555
