### ISSUE TITLE
Question: Return Client from function to JS

### ISSUE THREAD

**Issue by hg-gr** [devashishdxt/tonic-web-wasm-client#63]
Thanks a bunch for working on something so cool, I am able to get things to compile which is great. I want to try the following:

```rust
use market_data::global_pricing_service_client::GlobalPricingServiceClient;
use tonic_web_wasm_client::Client;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub async fn get_client() -> GlobalPricingServiceClient<Client> {
    let client = Client::new("http://localhost:50051".to_string());
    GlobalPricingServiceClient::new(client)
}
```

But my return type is not working, the error is that my GlobalPricingServiceClient type is not able to become a JS type.

Have you achieved something similar or are able to explain how I can do this? 

Thanks again!

**Comment by devashishdxt** [comment]
Hi. If you're trying to use this crate in JS. I'd suggest to use some pre-existing JS libraries to call web gRPC. This crate is primarily intended for use in Rust code that gets compiled to web assembly. If you still want to go the Rust route, you should be definitely be able to do this. I don't have a working example, but you can read how to do this here: https://rustwasm.github.io/docs/wasm-bindgen/
