### ISSUE TITLE
Cargo test/build on the repo fails. 

### ISSUE THREAD

**Issue by moehaque** [devashishdxt/tonic-web-wasm-client#8]
Hello,

Please go easy on me. I am really new at this and do not really know the process well enough. My apologies, if i am out of line here. 

build is failing likely due to version of reqwest. 11.3 has a fetch_credentials_same_origin and 11.11 does not. 

```
____________________:$ cargo test
   Compiling wasm-bindgen-futures v0.4.32
   Compiling tonic-web-wasm-client v0.2.1 (tonic-web-wasm-client)
   Compiling wasm-bindgen-test v0.3.32
error[E0599]: no method named `fetch_credentials_same_origin` found for struct `RequestBuilder` in the current scope
  --> src/client.rs:60:10
   |
60 |         .fetch_credentials_same_origin();
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `RequestBuilder`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `tonic-web-wasm-client` due to previous error
warning: build failed, waiting for other jobs to finish...`

```

Thank you

**Comment by devashishdxt** [comment]
Hi. You can only build this crate for `wasm` targets. Try `cargo build --target wasm32-unknown-unknown`.

**Comment by moehaque** [comment]
Thank you! Again. Very sorry!

**Comment by isosphere** [comment]
> Hi. You can only build this crate for `wasm` targets. Try `cargo build --target wasm32-unknown-unknown`.

In case this is helpful to someone else, you can make this the default for `cargo build` by creating a `.cargo` directory in your project with a file named `config`. Here's the contents of that file for my wasm project:

```
[build]
target = "wasm32-unknown-unknown"
```

This way when you return to your project in a year you won't hit this again when trying `cargo build`!

**Comment by devashishdxt** [comment]
Added a [`Building`](https://github.com/devashishdxt/tonic-web-wasm-client#building) section in readme.
